// Post-processes the wasm-pack output so the module can be instantiated from
// inlined bytes instead of fetch(new URL(..., import.meta.url)).
//
// wasm-bindgen's `--target web` glue defaults to fetching the .wasm via a URL
// resolved against import.meta.url. When a downstream app bundles scanic, that
// pattern breaks: Vite/esbuild mangle the inlined data: URL into a relative
// request (e.g. /node_modules/.vite/deps/data:application/wasm;base64...), the
// fetch fails, and the library silently falls back to JS. It also triggers a
// build-time "new URL(..., import.meta.url) doesn't exist at build time" warning.
// See https://github.com/marquaye/scanic/issues/7.
//
// We instead embed the wasm as base64 and pass the decoded bytes to init()
// (see src/edgeDetection.js), then neutralize the glue's dead fetch/URL branch.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const pkgDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'wasm_blur', 'pkg');
const wasmPath = path.join(pkgDir, 'wasm_blur_bg.wasm');
const gluePath = path.join(pkgDir, 'wasm_blur.js');
const base64Path = path.join(pkgDir, 'wasm_blur_bg_base64.js');

// 1. Inline the wasm bytes as base64.
const wasm = fs.readFileSync(wasmPath);
fs.writeFileSync(
  base64Path,
  `// Auto-generated by scripts/postprocess-wasm.mjs. Do not edit.\n` +
  `// Base64-encoded contents of wasm_blur_bg.wasm, inlined so the module can be\n` +
  `// instantiated without fetch()/new URL(import.meta.url).\n` +
  `export default '${wasm.toString('base64')}';\n`
);

// 2. Remove the glue's default fetch(new URL(..., import.meta.url)) path. scanic
//    always supplies the bytes, so this branch is dead code; deleting the
//    new URL(import.meta.url) token is what stops downstream bundler breakage.
let glue = fs.readFileSync(gluePath, 'utf8');
const needle = /module_or_path = new URL\('wasm_blur_bg\.wasm', import\.meta\.url\);/;
if (needle.test(glue)) {
  glue = glue.replace(needle, `throw new Error('scanic: WASM module bytes must be passed to init().');`);
  fs.writeFileSync(gluePath, glue);
  console.log('postprocess-wasm: inlined base64 + patched wasm_blur.js (removed import.meta.url fetch path).');
} else if (glue.includes('WASM module bytes must be passed to init()')) {
  console.log('postprocess-wasm: inlined base64; glue already patched.');
} else {
  console.warn('postprocess-wasm: WARNING: could not find the new URL(import.meta.url) line; wasm-bindgen glue format may have changed.');
}
